- name: Update and upgrade packages
  package:
    name: '*'
    state: latest

- name: Install git client
  package:
    name: git 
    state: latest

- name: Config host lab ansible
  lineinfile: 
      dest: /etc/hosts
      state: present
      line: "{{ item }}"  
  with_items: 
    - 192.168.56.2 control-node
    - 192.168.56.3 app-01
    - 192.168.56.4 db-01