---
- name: Config app server java
  hosts: app-01

  user: vagrant
  become: yes

  vars:
    - dbhost: "db-01"
    - dbname: "notes"
    - dbusername: "notesapp"
    - dbpassword: "devops"

  tasks:
    - name: Config host lab ansible
      lineinfile: 
        dest: /etc/hosts
        state: present
        line: "{{ item }}"  
      with_items: 
        - 192.168.56.2 control-node
        - 192.168.56.3 app-01
        - 192.168.56.4 db-01
    - name: User add app
      user:
        name: app
        comment: application user
        uid: 500

    - name: Maven Install
      get_url:
        url: https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.1.0/apache-maven-3.1.0-bin.tar.gz
        dest: /opt/apache-maven-3.1.0-bin.tar.gz

    - name: Unzip maven package
      ansible.builtin.unarchive:
        src: /opt/apache-maven-3.1.0-bin.tar.gz
        dest: /opt/
        remote_src: yes  

    - name: Java Install
      package:
        name: java-1.8.0-openjdk
        state: latest 
      
    - name: Make dir app
      file:
        path: /opt/notes
        state: directory
        owner: app
        group: app

    - name: Install git client
      package:
        name: git 
        state: latest

    - name: Repo clone notes-app
      git:
        repo:  'https://github.com/callicoder/spring-boot-mysql-rest-api-tutorial.git'
        dest: /opt/notes
        clone: yes
        force: yes

    - name: Config pom.xml repo maven central
      template:
        src: pom.xml
        dest: /opt/notes/pom.xml

    - name: Config file owner dbase layer
      template:
        src: application.properties
        dest: /opt/notes/src/main/resources/apllication.properties

    - name: Make package app
      command: /opt/apache-maven-3.1.0/bin/mvn -f /opt/notes/pom.xml package
      become_user: app

    - name: Version register app
      shell:
        cmd: /opt/apache-maven-3.1.0/bin/mvn org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version | grep -v '\['
        chdir: /opt/notes/
      register: app_version 

    - name: Systemd Config service
      template:
        src: etc/systemd/system/notes.service
        dest: etc/systemd/system/notes.service
      notify: reload daemon

    - name: Start service notes-app
      service:
        name: notes
        state: restarted
  roles:
    - config-default-so
  handlers:
    - name: reload app
      systemd:
        state: restarted
        daemon_reloado: yes
        name: 'notes'
    - name: reload daemon
      systemd:
        daemon_reexec: yes 

    

