---
- name: Config server DB
  hosts: db-01
  user: vagrant
  become: yes
  vars_files:
    - vars/main.yml
  vars:
    - dbname: "db-01"
    - dbusername: "root"
    - dbpassword: "devops"
    
  roles:
    - config-default-so
    - role: geerlingguy.mysql

      

