Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"

  config.vm.network "forwarded_port", guest: 80, host: 8080


  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

 
  # config.vm.network "private_network", ip: "192.168.33.10"

  # config.vm.network "public_network"


   config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
     
  vb.memory = "2048"
   end


   config.vm.provision "shell",path: "provision.sh"
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
